include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false
    avoid_catches_without_on_clauses: false
    document_ignores: false

analyzer:
  exclude:
    - '**/*.freezed.dart'
    - '**/*.g.dart'